export const SET_BOARD_INITIAL_STATE = 'SET_BOARD_INITIAL_STATE';
export const SET_SHIP_POSITION= 'SET_SHIP_POSITION';
export const SET_SHIP_DRAGGED= 'SET_SHIP_DRAGGED';
export const SHOOT_CELL = 'SHOOT_CELL';